# This is a workflow to get the design examples of https://github.com/altera-fpga/settings/blob/main/predefined_url.json

name: Get Design Examples

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  get-design-examples:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Get design examples
        run: ls -la 
