# This is a workflow to get the design examples of https://github.com/altera-fpga/settings/blob/main/predefined_url.json

name: Get Predefined Design Examples

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  get-design-examples:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
          
      - name: Install Python Dependencies
        shell: bash
        run: pip install -r scripts/requirements.txt

      - name: Get design examples
        run: python scripts/get_design_examples.py
